spring.application.name=subscription-service-twitterlike


logging.level.com.masterilidan.subscriptionservicetwitterlike=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_database
spring.data.jdbc.dialect=h2
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8082

url.baseUrl.UserService=localhost:8080
url.baseUrl.MessageService=localhost:8081
url.baseUrl.SubsService=localhost:8082
